# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.27
_src_path: gh:OCA/oca-addons-repo-template
additional_ruff_rules: []
ci: GitHub
convert_readme_fragments_to_markdown: true
enable_checklog_odoo: false
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_test_flavor: Odoo
odoo_version: 17.0
org_name: rrebollo
org_slug: rrebollo
rebel_module_groups: []
repo_description: Design patterns playground within odoo
repo_name: sim-u-duck-app
repo_slug: sim-u-duck-app
repo_website: https://github.com/rrebollo/sim-u-duck-app
use_pyproject_toml: true
use_ruff: true

